// obfuscated.cpp ù generated by generate.py. DO NOT EDIT BY HAND.
// CFG-flattened license-key check with anti-debug/anti-VM probes mixed
// into the state-transition arithmetic.

#include <cstdio>
#include <cstring>
#include <cstdint>
#include "anti_probes.h"

static int check_key(const char* k) {
    int  result = 0;
    int  nibbles[12] = {0};
    int  idx = 0;
    int  sum = 0;
    unsigned g1 = 0, g2 = 0, g3 = 0;

    const int TERM = -1;
    int state = 0;

    while (state != TERM) {
        int next = TERM;
        switch (state) {
            case 0: {
                if (std::strlen(k) != 14) { result = 0; next = TERM; }
                else                      { next = 1; }

                break;
            }
            case 1: {
                if (k[4] != '-' || k[9] != '-') { result = 0; next = TERM; }
                else                            { next = 2; }

                break;
            }
            case 2: {
                idx = 0;
                bool ok = true;
                for (int i = 0; i < 14; ++i) {
                if (i == 4 || i == 9) continue;
                char c = k[i];
                int v = -1;
                if      (c >= '0' && c <= '9') v = c - '0';
                else if (c >= 'a' && c <= 'f') v = 10 + (c - 'a');
                else if (c >= 'A' && c <= 'F') v = 10 + (c - 'A');
                if (v < 0) { ok = false; break; }
                nibbles[idx++] = v;
                }
                if (!ok) { result = 0; next = TERM; } else { next = 3; }

                break;
            }
            case 3: {
                sum = 0;
                for (int i = 0; i < 12; ++i) sum += nibbles[i];
                if ((sum & 0xF) != 0xA) { result = 0; next = TERM; } else { next = 4; }

                break;
            }
            case 4: {
                g1 = (nibbles[0]<<12) | (nibbles[1]<<8) | (nibbles[2]<<4) | nibbles[3];
                g2 = (nibbles[4]<<12) | (nibbles[5]<<8) | (nibbles[6]<<4) | nibbles[7];
                g3 = (nibbles[8]<<12) | (nibbles[9]<<8) | (nibbles[10]<<4) | nibbles[11];
                next = 5;

                break;
            }
            case 5: {
                if ((g1 ^ g2 ^ g3) != 0xBEEFu) { result = 0; next = TERM; }
                else                           { result = 1; next = TERM; }

                break;
            }
            default:
                // Invalid state (probe-derailed or corruption). Terminate with failure.
                result = 0;
                next   = TERM;
                break;
        }
        // Mix anti-analysis probe mask into the next-state.
        // Clean run: probe_mask() == 0, state == next.
        // Under debugger/VM: probe_mask() != 0, state jumps to an invalid case.
        if (next == TERM) {
            state = TERM;
        } else {
            state = next ^ (int)probe_mask();
        }
    }
    return result;
}

int main(int argc, char** argv) {
    if (argc != 2) {
        std::printf("usage: %s <key>\n", argv[0]);
        return 2;
    }
    std::printf("%s\n", check_key(argv[1]) ? "OK" : "BAD");
    return 0;
}
